# To create, use mamba (or conda):
# mamba env create -f environment.yml
# To recreate from scratch, remove previously created environment first:
# mamba remove -n d23b-ice-dependence --all
name: d23b-ice-dependence
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - notebook
  - numpy>=1.14
  - scipy
  - pandas
  - xarray
  - NetCDF4
  - matplotlib
  - seaborn
  - watermark
  - pybind11>=2.4
  - setuptools>=30.3.0
  - setuptools_scm>=2.0.0
  - pip
  - pip:
      - pyvinecopulib
